// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJyv0EkKNC0gVpf1jvgIrVtn1I2JFxN4E',
    appId: '1:479610373068:web:32dff2339ac1e997165369',
    messagingSenderId: '479610373068',
    projectId: 'kuizer-demo-4a44f',
    authDomain: 'kuizer-demo-4a44f.firebaseapp.com',
    storageBucket: 'kuizer-demo-4a44f.appspot.com',
    measurementId: 'G-B1CH2QR6D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOONqc4NQYirFGwdh1mVCrHs7uZnCl2Zo',
    appId: '1:479610373068:android:820c5d7c2f5f7ca5165369',
    messagingSenderId: '479610373068',
    projectId: 'kuizer-demo-4a44f',
    storageBucket: 'kuizer-demo-4a44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6JVa5i-asVIrVM3if9Ltet871syv3Hw',
    appId: '1:479610373068:ios:5e7e5848f64b2feb165369',
    messagingSenderId: '479610373068',
    projectId: 'kuizer-demo-4a44f',
    storageBucket: 'kuizer-demo-4a44f.appspot.com',
    iosClientId: '479610373068-apu6o4ni6cg764c7s89pkpbkag29nr50.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuizer',
  );
}
